# Generated by Django 5.0.4 on 2024-05-29 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='r_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 16, 20, 37, 686101, tzinfo=datetime.timezone.utc)),
        ),
    ]
